Repository open-source-botany/growlog, pull requests merged in 2018-10, with the labels that each got.

#10 Fix CI Build
  tox.ini
Labels: bug

#8 Add tests for growlog.main methods Fixes #5
  tests/test_main.py
  tox.ini
Labels: hacktoberfest, tests

#12 Remove py33 from AppVeyor build
  appveyor.yml
Labels: bug, hacktoberfest
